authors:
  cj:
    name: Cj "csubj" Buresch
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/1504746
  trent:
    name: Trent "spacekek" Clostio
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/14352895
  jacob:
    name: Jacob "yakl / yacklebeam" Martinez-Troxel
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/1591749
  nathan:
    name: Nathaniel "kag0" Fischer
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/3280689

# - name: Cj "csubj" Buresch
#   bio : I came for the free food but now I've been here too long to just leave.
#   websites:
#     - name: github
#       url : https://github.com/CjBuresch
#     - name: twitter
#       url : https://twitter.com/csubj

# - name: Trent "spacekek" Clostio
#   bio : Senior security engineer, hacker, recovering developer. I'm drinking all of the booze and hacking all of the things. No longer pursuing CS masters.
#   websites:
#     - name: github
#       url : https://github.com/tclostio?tab=repositories
#     - name: more
#       url : https://trent.clost.io

# - name: Nathaniel "kag0" Fischer
#   bio : Surfing the mortal coil; witness to the sunset of man. 
#   websites:
#     - name: github
#       url: https://github.com/kag0
#     - name: keybase
#       url: https://keybase.io/nfischer

# - name: Jacob "yakl / yacklebeam" Martinez-Troxel
#   bio : Software engineer. Would rather be a lumberjack at this point.
#   websites:
#     - name: gitlab
#       url: https://gitlab.com/yacklebeam
#     - name: github
#       url: https://github.com/yacklebeam?tab=repositories
#     - name: about
#       url : https://yakl.dev
